### ISSUE TITLE
current version doesn't work in Chrome?

### ISSUE THREAD

**Issue by Luckz** [Nuklon/Steam-Economy-Enhancer#1]
I've been using this for a while in Firefox, and while the old version updated to the current works in my Firefox, in my friend's Chrome and my own Chrome a fresh install of the newest version doesn't work.

**Comment by Luckz** [comment]
Old version https://github.com/Nuklon/Steam-Economy-Enhancer/raw/ba8bcdd045fc88ed04a84f0354bd09311befa32d/code.user.js does however work.

**Comment by Gargauth** [comment]
Same issue here. It seems it's because of this line

`var user_currency = window.GetCurrencySymbol(window.GetCurrencyCode(market.walletInfo.wallet_currency));`

output in Chrome console:

`ERROR: Execution of script 'Steam Economy Enhancer' failed! window.GetCurrencyCode is not a function`

**Comment by Gargauth** [comment]
Okay, I did a quick research and it seems problem is caused by this: http://stackoverflow.com/a/5006952

Possible workarounds:

```// @grant       unsafeWindow
var user_currency = unsafeWindow.GetCurrencySymbol(unsafeWindow.GetCurrencyCode(market.walletInfo.wallet_currency));```
or
```// @require     http://steamcommunity.com/public/javascript/global.js
var user_currency = GetCurrencySymbol(GetCurrencyCode(market.walletInfo.wallet_currency));```

I don't know much about javascript/Greasemonkey to know all implications of these changes. The second approach seems to be _cleaner_ as usage of unsafeWindow is adviced against whenever possible both for security sake as well as it may incur compatibility issues between browsers.

**Comment by Nuklon** [comment]
Thanks for the research, I have it fixed, will upload a new build soon.
