### ISSUE TITLE
"success" is not checked when selling items

### ISSUE THREAD

**Issue by xPaw** [Nuklon/Steam-Economy-Enhancer#109]
The log will say `1 / 1 - :csgo_loser: listed for 0.02€, you will receive 0.00€.`

But the server response is `{"success":false,"message":"There was a problem listing your item. Refresh the page and try again."}` (HTTP 200).

I kinda fixed this by setting minimum price to `0.03` so it doesn't try to list with incorrect price.

**Comment by jbmccune** [comment]
This isn't limited to the low price issue - the flaky Steam market can return this error quite often.  I just tried to re-list a couple hundred overpriced items from my market listing, and they all supposedly succeeded, but in reality I just ended up with a couple hundred items in my inventory (it de-listed them fine).  I then tried to list them all from my inventory, and again it said they all succeeded, but there were no pending confirmations, and they are all still sitting in my inventory.  I then tried to sell one item using the generic Steam functionality, and I constantly get the "There was a problem listing your item.  Refresh the page and try again." error (refreshing the page doesn't help at all).  If I keep clicking OK, eventually it succeeds, and then there seems to be a small window where SEE sales will also go through.

I think this is just caused by Steam being buggy, but the problem with SEE is the faulty error handling.

**Comment by Nuklon** [comment]
I originally checked success but also found that very unreliable. Perhaps that's a little better now, I don't know. The entire market is extremely buggy anyway, I very often have 'ghost' listings that do not show up in confirm app but are visible on market page to confirm.

**Comment by jbmccune** [comment]
> I very often have 'ghost' listings that do not show up in confirm app but are visible on market page to confirm.
Yeah, out of a batch of 250 listings, I almost always have at least a few of those, which means I go confirm everything, then go to the market page and clear out the orphaned pending ones before starting the next batch.  It's a pain.  They seem to be duplicates - my suspicion is that the first attempt to list an item "fails", and a retry succeeds.  The failed attempt actually succeeds though in some kind of disconnected state, resulting in an extra, broken pending confirmation for the same item.
