### ISSUE TITLE
"View in Community Market" Link is Missing

### ISSUE THREAD

**Issue by Bonsai99** [Nuklon/Steam-Economy-Enhancer#112]
#79 #93 

Only seems to be working properly on Steam Items - does not work on TF2, CS:GO, etc.

Tested with all other extensions/scripts disabled to make sure nothing was interfering,

**Comment by LeMarkel** [comment]
Yep this is the worst, especially because it's there for less than a fraction of a second while the extension loads information from the very URL it then causes to disappear.  Not being able to access the page with the interactive market history graph and current buy/sell offers including your own is quite a QoL step backwards.
