### ISSUE TITLE
Loading the webpage takes forever

### ISSUE THREAD

**Issue by woctezuma** [Nuklon/Steam-Economy-Enhancer#144]
Starting today, it seems that loading the market homepage or the inventory takes forever. It works fine after the user-script is disabled.

**Comment by gx240** [comment]
I just started having problems with the script today. It locks up on the Steam inventory page. If I wait long enough, the page eventually loads, but the script doesn't run.

**Comment by Floyd77** [comment]
I have this problem too with Firefox and Violentmonkey, but it still works well with Chrome and Tampermonkey.

**Comment by woctezuma** [comment]
You might be onto something, because I am using the Firefox+ViolentMonkey combo.

**Comment by Floyd77** [comment]
I downgraded to version [2.12.14](https://addons.mozilla.org/en-US/firefox/addon/violentmonkey/versions/) and it works again, so it is definitely a problem with the latest Violentmonkey update for Firefox.

If you want to downgrade don't forget to backup your userscripts because you have to uninstall the current version first.

**Comment by Floyd77** [comment]
I [reported](https://github.com/violentmonkey/violentmonkey/issues/861) this bug to the Violentmonkey developers and they just [released a fix](https://github.com/violentmonkey/violentmonkey/releases/tag/v2.12.6). Update to 2.12.6 and it will be solved.

**Comment by woctezuma** [comment]
Thank you!
