### ISSUE TITLE
still getting banned

### ISSUE THREAD

**Issue by pacopepepipo** [Nuklon/Steam-Economy-Enhancer#168]
Today while browsing my inventory an selling some cards, I was clicking on some of them to see the prices they had, and I've been banned from seeing the items on sale and prices 3 times

I didn't need to go to the market and open 10 pages, just clicking through some cards randomly on my inventory to find if I needed to adjust the prices manually and selling them some manually, some automatically after selecting a range with "click and sift", I've been hit with the limit and a ban 

If you click on the "sell cards" or "sell items" and do not do anything, there is no problem, but if you click on multiple of them, the problem comes again

so the issue is still there and not solved as the other thread was locked and marked as it.

**Comment by Nuklon** [comment]
Works for me, can't fix this any further.

**Comment by woctezuma** [comment]
Just a quick observation, but I don't have time to investigate this further for now: this rate-limit issue might be tied to listings of "booster packs" rather than "trading cards".

**Comment by Spyroflex** [comment]
The script also works fine for me but I have no idea why honestly. 
For my own purpose I've been trying to figure out how to make more than 10 steamcommunity.com/market/itemordershistogram requests without getting rate limited but no matter what I do: adding the same params as the script, changing params in every way possible, sending cookies, not sending cookies, using different IPs with a VPN, use the browser directly instead of using get in python, using the browser while not logged in, using different user agents, different browsers and even different devices... 

The script works fine, opening more than 10 different market pages works fine. It should be the exact same but making more than 10 itemordershistogram requests for different items always gives me an instant 429 error. Any ideas?
