### ISSUE TITLE
Market Problem

### ISSUE THREAD

**Issue by OliverTrust** [Nuklon/Steam-Economy-Enhancer#222]
### Describe the bug

After this update https://github.com/Nuklon/Steam-Economy-Enhancer/commit/c2a4d305ad691518de627f9084d9e7bc37dfd559 i have a problem with relist overpriced market listings. All my items on market marked as overpriced. My currency is RUB. Previous version work without any problems 

version with problem
![1](https://github.com/user-attachments/assets/2558dfae-0a2c-4bbd-8c5b-eb8e89c8e62d)
version without problem
![2](https://github.com/user-attachments/assets/6a4199e3-9a8b-4466-a952-6817878108bf)

### Browser name and version

chrome 127.0.6533.100

**Comment by xPaw** [comment]
wtf valve, their russian "currency symbol" has a latin "p" instead of cyrillic one.

So it's failing to strip it from the amount, causing the bug.

> `GetCurrencySymbol( 'RUB' )`
'pуб.'

![image](https://github.com/user-attachments/assets/2b4335a8-4ecc-4f07-bc23-93a11d050546)

**Comment by OliverTrust** [comment]
Yes, i have the same result

**Comment by xPaw** [comment]
Then I'm not sure why it would cause issues, 0,47rub should parse to 47, the bug is some multiplier to 100 somewhere.

**Comment by SeRi0uS007** [comment]
It seems that using `unsafeWindow.GetPriceValueAsInt` from raw jQuery `text()` can lead to unpredictable script behavior.

I have exactly the same problem (my currency is ₴).
But I have stacked items for sale.
![img1](https://github.com/user-attachments/assets/5f84b1d9-6ce0-4c0d-9342-53303619e5de)

Because of the dot at the end, the `GetPriceValueAsInt` function doesn't work as it should.

In addition, priceSeller receives the price in parentheses `(0.03₴)` as an argument, which is why `GetPriceValueAsInt` simply returns 0...

![img2](https://github.com/user-attachments/assets/2cc78374-3749-4846-8273-34e9f5b1dcb8)

**Comment by xPaw** [comment]
> Because of the dot at the end, the GetPriceValueAsInt function doesn't work as it should.

That "/piece." is definitely problematic, didn't know this is even a thing. I don't know if just removing last dot will work for all languages here.

And for seller price, just stripping () should work. Wanna make a PR?

**Comment by xPaw** [comment]
There shouldn't be strings in market with that many dots, so that's fine.

**Comment by xPaw** [comment]
> their russian "currency symbol" has a latin "p" instead of cyrillic one.

well that was fixed after today's maintenance
