### ISSUE TITLE
Failed to execute 'setItem' on 'Storage'

### ISSUE THREAD

**Issue by Royalgamer06** [Nuklon/Steam-Economy-Enhancer#3]
I get this error pretty often:

![](https://i.imgur.com/EQuyDuW.pngl)

The first error is from "Selling all cards" and the second error is from "Selling all items".
Sometimes I can resolve it by manually selling the items causing a problem.
I think you are saving too much data in storage.
I also tried using GM_setValue/GM_getValue instead, but it pretty much gives the same issue.
I am using 64-bit Google Chrome.

BTW, I've discovered this quite recently, but for constant variables, you can use "const" instead of "var". You could use that for your constants.

**Comment by Nuklon** [comment]
It's indeed because local/session storage has size limitations. Even with my 200+ cards in the market I've yet to reach the limit in Firefox. 

I think the GM_... functions have the same limitations.

I always thought it was 5MB per entry (which is extremely unlikely to reach per entry as it's just a few KB's of Json) but perhaps it's 5MB in total in Chrome. 

Regardless, this error can be catched, and I'll update it :) 
(It's just for caching and it shouldn't fail)

**Comment by Royalgamer06** [comment]
Hmm weird, I tried deleting localStorage, but I would still get the error. Anyway, thanks for fixing it! I have one other small request, but I'll make a separate ticket for it.
