### ISSUE TITLE
Lags like crap and uses different prices when listing in bulk

### ISSUE THREAD

**Issue by lib2k** [Nuklon/Steam-Economy-Enhancer#59]
Performance is frankly utter shit, rendering the use of this script slow and unbearable after loading 4 or 5 consecutive inventory pages before having to close and reopen the tab. I don't know how well versed you are with JS but anything big query without proper caching is going to drag it completely down. Then I need twice as long to do what I wanted to do due to waiting time, reloads or inventory freezes.
  
Also whats with this fucking random pricing when selling in bulk? I select 30 cards and they have to go for the same price, yet this crap will list them wildly different, 12 cent, 5 cent, 8 cent et cetera, half of them have to be cancelled due to unwanted and unsatisfying pricing. That's double the mundane work, than listing them by hand.

**Comment by Nuklon** [comment]
Please go fuck yourself, this has no point but bashing.
On Nov 1, 2017, at 17:21, lib2k <notifications@github.com<mailto:notifications@github.com>> wrote:

Performance is frankly utter shit, rendering the use of this script slow and unbearable after loading 4 or 5 consecutive inventory pages before having to close and reopen the tab. I don't know how well versed you are with JS but anything big query without proper caching is going to drag it completely down. Then I need twice as long to do what I wanted to do due to waiting time, reloads or inventory freezes.

Also whats with this fucking random pricing when selling in bulk? I select 30 cards and they have to go for the same price, yet this crap will list them wildly different, 12 cent, 5 cent, 8 cent et cetera, half of them have to be cancelled due to unwanted and unsatisfying pricing. That's double the mundane work, than listing them by hand.

**Comment by lib2k** [comment]
Blatantly honest criticism on whats wrong with this, nothing else.
Anyway I found a clean version of SIH, so you can keep jerking off your fragile feelings here. Case closed, I'm out.

**Comment by Nuklon** [comment]
Good for you, bye.
On Nov 1, 2017, at 17:52, lib2k <notifications@github.com<mailto:notifications@github.com>> wrote:

Blatantly honest criticism on whats wrong with this, nothing else.
Anyway I found a clean version of SIH, so you can keep jerking off your fragile feelings here. Case closed, I'm out.
